### ISSUE TITLE
Merge command doesn't need to generate OpenAPI

### ISSUE THREAD

**Issue by kgilpin** [getappmap/archive-action#21]
This line is unnecessary:

https://github.com/getappmap/archive-action/blob/9b1167a49aeb63cae66ffb23eb36ddca52efa109/src/merge.ts#L97

Because even with `--no-index`, the archive command generates OpenAPI:

https://github.com/getappmap/appmap-js/blob/1a9caddcf49655c094bc9b4148a2f8d9deaaf214/packages/cli/src/cmds/archive/archive.ts#L191

Steps to implement:

* Remove the OpenAPI generation step from the merge command.
* Update tests as needed
* Verify that CI analysis works as designed by running a matrix build pointing to this branch of the merge action.

@petecheslock what's a good matrix build to modify in order to test this fix?

**Comment by kgilpin** [comment]
Done

**Comment by petecheslock** [comment]
Oh missed this @kgilpin if you need a good matrix build its probably this one right now https://github.com/land-of-apps/sample_django_app/blob/appmap/.github/workflows/appmap-analysis.yml
