### ISSUE TITLE
archive-action should not write the Welcome message when archive-id is set

### ISSUE THREAD

**Issue by kgilpin** [getappmap/archive-action#31]
`archive-id` indicates that the archive action is being used in a matrix build. In that case, do not write the Welcome message to the PR description; otherwise there will be one Welcome message for each matrix build container.

Instead, the Welcome message should be written by the `archive-action/merge` action.

**Comment by petecheslock** [comment]
@kgilpin i've gotten a sizable django project working with multiple runners that we can use to test this out - you'll see in the PR multiple reports getting written.  https://github.com/land-of-apps/sample_django_app/pull/6/files

**Comment by kgilpin** [comment]
Done
